# Generated by Django 4.1.4 on 2023-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inovice_id', models.CharField(max_length=255, unique=True)),
                ('payment', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
            ],
        ),
    ]
